### ISSUE TITLE
Server crash on startup when used with Luckperms

### ISSUE THREAD

**Issue by Justsnoopy30** [Ladysnake/Impersonate#7]
```[18:29:41] [Server thread/ERROR] (Minecraft) Encountered an unexpected exception
 java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8450()" because the return value of "net.minecraft.server.MinecraftServer.method_30002()" is null
        at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.5) ~[?:?]
        at net.minecraft.server.MinecraftServer.getGameRules(MinecraftServer:1463) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.localvar$znf000$revealImpersonatorsInMessages(MinecraftServer:2725) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.sendSystemMessage(MinecraftServer) ~[intermediary-server.jar:?]
        at net.minecraft.server.command.ServerCommandSource.sendFeedback(ServerCommandSource:215) ~[?:?]
        at me.lucko.luckperms.fabric.FabricSenderFactory.sendMessage(FabricSenderFactory.java:80) ~[LuckPerms-Fabric-5.3.16.jar:?]
        at me.lucko.luckperms.fabric.FabricSenderFactory.sendMessage(FabricSenderFactory.java:44) ~[LuckPerms-Fabric-5.3.16.jar:?]
        at me.lucko.luckperms.common.sender.AbstractSender.sendMessage(AbstractSender.java:85) ~[LuckPerms-Fabric-5.3.16.jar:?]
        at me.lucko.luckperms.common.locale.Message$Args1.send(Message.java:4059) ~[LuckPerms-Fabric-5.3.16.jar:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:117) ~[LuckPerms-Fabric-5.3.16.jar:?]
        at me.lucko.luckperms.fabric.LPFabricBootstrap.onServerStarting(LPFabricBootstrap.java:146) ~[LuckPerms-Fabric-5.3.16.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:37) ~[77dfdc3a-f1c7-477e-a321-79b82f1c8a7a.jar:?]
        at net.minecraft.server.MinecraftServer.handler$znl000$beforeSetupServer(MinecraftServer:3238) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:645) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[18:29:41] [Server thread/ERROR] (Minecraft) This crash report has been saved to: /home/justsnoopy30/Projects/Minecraft Servers/Fabric/SMP/./crash-reports/crash-2021-03-29_18.29.41-server.txt
[18:29:41] [Server thread/INFO] (Beacon) Disabling Beacon v0.7.2...
[18:29:41] [Server thread/INFO] (Beacon) Disabling plugins has not been implemented yet!
[18:29:41] [Server thread/INFO] (Beacon) Disabled Beacon v0.7.2!
[18:29:41] [Server thread/INFO] (luckperms) Starting shutdown process...
[18:29:41] [Server thread/ERROR] (Minecraft) Exception stopping the server
 java.lang.NullPointerException: Cannot invoke "me.lucko.luckperms.common.treeview.PermissionRegistry.close()" because "this.permissionRegistry" is null
        at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.5) ~[?:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.disable(AbstractLuckPermsPlugin.java:228) ~[LuckPerms-Fabric-5.3.16.jar:?]
        at me.lucko.luckperms.fabric.LPFabricBootstrap.onServerStopping(LPFabricBootstrap.java:150) ~[LuckPerms-Fabric-5.3.16.jar:?]
        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$4(ServerLifecycleEvents.java:62) ~[77dfdc3a-f1c7-477e-a321-79b82f1c8a7a.jar:?]
        at net.minecraft.server.MinecraftServer.handler$znl000$beforeShutdownServer(MinecraftServer:3248) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.shutdown(MinecraftServer) ~[intermediary-server.jar:?]
        at net.minecraft.server.dedicated.MinecraftDedicatedServer.shutdown(MinecraftDedicatedServer:567) ~[?:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:707) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]```

**Comment by wesleytech** [comment]
this crash also happens with the latest version of luckperms, 5.3.30
impersonate version: 2.1.0

**Comment by DillonB07** [comment]
Same issue here with latest versions of each.
Log:
```
[ERROR] Encountered an unexpected exception

java.lang.NullPointerException: null

at net.minecraft.server.MinecraftServer.method_3767(MinecraftServer.java:1463) ~[intermediary-server.jar:?]

at net.minecraft.server.MinecraftServer.localvar$zip000$revealImpersonatorsInMessages(MinecraftServer.java:3225) ~[intermediary-server.jar:?]

at net.minecraft.server.MinecraftServer.method_9203(MinecraftServer.java) ~[intermediary-server.jar:?]

at net.minecraft.class_2168.method_9226(class_2168.java:215) ~[intermediary-server.jar:?]

at me.lucko.luckperms.fabric.FabricSenderFactory.sendMessage(FabricSenderFactory.java:80) ~[LuckPerms-Fabric-5.3.21.jar:?]

at me.lucko.luckperms.fabric.FabricSenderFactory.sendMessage(FabricSenderFactory.java:44) ~[LuckPerms-Fabric-5.3.21.jar:?]

at me.lucko.luckperms.common.sender.AbstractSender.sendMessage(AbstractSender.java:85) ~[LuckPerms-Fabric-5.3.21.jar:?]

at me.lucko.luckperms.common.locale.Message$Args1.send(Message.java:4066) ~[LuckPerms-Fabric-5.3.21.jar:?]

at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:117) ~[LuckPerms-Fabric-5.3.21.jar:?]

at me.lucko.luckperms.fabric.LPFabricBootstrap.onServerStarting(LPFabricBootstrap.java:146) ~[LuckPerms-Fabric-5.3.21.jar:?]

at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:37) ~[6592a7d2-3225-4477-973f-ef6072c68003.jar:?]

at net.minecraft.server.MinecraftServer.handler$zka000$beforeSetupServer(MinecraftServer.java:3738) ~[intermediary-server.jar:?]

at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645) ~[intermediary-server.jar:?]

at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

[ERROR] This crash report has been saved to: /home/gs-40896/./crash-reports/crash-2021-05-01_16.58.09-server.txt

[ERROR] Exception stopping the server

java.lang.NullPointerException: null

at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[custom.jar:?]

at com.sk89q.worldedit.extension.platform.PlatformManager.unregister(PlatformManager.java:125) ~[worldedit-mod-7.2.4.jar:?]

at com.sk89q.worldedit.fabric.FabricWorldEdit.onStopServer(FabricWorldEdit.java:229) ~[worldedit-mod-7.2.4.jar:?]

at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$4(ServerLifecycleEvents.java:62) ~[6592a7d2-3225-4477-973f-ef6072c68003.jar:?]

at net.minecraft.server.MinecraftServer.handler$zka000$beforeShutdownServer(MinecraftServer.java:3748) ~[intermediary-server.jar:?]

at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java) ~[intermediary-server.jar:?]

at net.minecraft.class_3176.method_3782(class_3176.java:567) ~[intermediary-server.jar:?]

at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:707) ~[intermediary-server.jar:?]

at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by Pyrofab** [comment]
Thanks for the report! It should be fixed now.
